# Generated by Django 5.2.3 on 2025-06-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='catergory',
            new_name='category',
        ),
    ]
